### ISSUE TITLE
difference in calculate_shortfall and calculate_lgcs

### ISSUE THREAD

**Issue by nick-gorman** [EllieKallmier/ppa_analysis#9]
Why are shortfall calculations based on 'Hybrid' volume for  'Baseload' and 'Shaped' contracts but lgc cacluation based on 'Contracted Energy'?

**Comment by EllieKallmier** [comment]
I probably need to fix up some of the wording/naming here to clarify these bill calculation bits.

The LGC calculations made in calculate_lgcs function refer to the buyer's need to either purchase more (or on-sell) LGCs in order to meet the set target for LGC coverage on aggregate across the settlement period (e.g. if annual, meeting 100% of total annual load with LGCs). This assumes that any contracted LGCs are delivered by the seller, so the remaining under/over supply of certificates then must be handled by the buyer.

The shortfall calculations made in calculate_shortfall function refer to the seller's need to make good any undelivered contracted energy - so the 'Hybrid' column shows the actual generation delivered in each period, and if it falls under the 'Contracted Energy' value in that period (for a Shaped or Baseload contract with set hourly values) then a shortfall penalty is applied.
